version: '3.8'

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "localstack-vol:/tmp/localstack" #use a volume not a path
      # - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack-vol:
    #declare the volume for the compose file

